### ISSUE TITLE
Arkansas data unavailable

### ISSUE THREAD

**Issue by Scotsman143** [QuantGov/regcensus-api-python#16]
Currently running into a issue with pulling data from Arkansas. I receive a warning saying that I can't call data for Arkansas because the jurisdiction doesn't exist (`jurisdictionID=99`). When I print a list of jurisdictions, though, Arkansas is available and lists its ID. I have a list of the southeast region, and when I remove Arkansas the jurisdiction argument works for `get_values`. Haven't seen this issue with any other state. I'm working with Kofi who identified it as a potential bug.
<img width="738" alt="Arkansas bug" src="https://user-images.githubusercontent.com/55407965/110541442-beb7ee00-80f5-11eb-877b-e6ffaf4048e2.png">

**Comment by jnelson16** [comment]
Good catch. Your calls are all correct, but we do not have RegData for Arkansas just yet, so there will not be any series 1 data for that jurisdiction.
